// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vista.Data;

#nullable disable

namespace Vista.Data.Migrations
{
    [DbContext(typeof(BomberosDbContext))]
    [Migration("20241001121703_SAguaAdd")]
    partial class SAguaAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Vista.Data.Models.Personales.BomberoDependencia", b =>
                {
                    b.Property<int>("BomberoDependenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BomberoDependenciaId"));

                    b.Property<int?>("DependenciaId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("BomberoDependenciaId");

                    b.HasIndex("DependenciaId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("BomberoDependencia", (string)null);
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.BomberoSalida", b =>
                {
                    b.Property<int>("BomberoSalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BomberoSalidaId"));

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MovilId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasKey("BomberoSalidaId");

                    b.HasIndex("MovilId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("SalidaId");

                    b.ToTable("BomberosSalida");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Brigada", b =>
                {
                    b.Property<int>("BrigadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrigadaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("BrigadaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Brigadas");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Comunicacion", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext");

                    b.Property<string>("NroEquipo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NroSerie")
                        .HasColumnType("longtext");

                    b.HasKey("EquipoId");

                    b.HasIndex("NroEquipo")
                        .IsUnique();

                    b.ToTable("Comunicacion", (string)null);
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Contacto", b =>
                {
                    b.Property<int>("ContactoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContactoId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoCel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TelefonoFijo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TelefonoLaboral")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ContactoId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Dependencia", b =>
                {
                    b.Property<int>("DependenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DependenciaId"));

                    b.Property<string>("NombreDependencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("DependenciaId");

                    b.ToTable("Dependencia", (string)null);
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Fuerza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreFuerza")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fuerzas");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.FuerzaInterviniente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DamnificadoId")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .HasColumnType("longtext");

                    b.Property<string>("Encargado")
                        .HasColumnType("longtext");

                    b.Property<int>("FuerzaId")
                        .HasColumnType("int");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DamnificadoId");

                    b.HasIndex("FuerzaId");

                    b.HasIndex("SalidaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("fuerzaIntervinientes");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.HorarioBombero", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HorarioId"));

                    b.Property<int>("BomberoId")
                        .HasColumnType("int");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("HoraDesde")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModoRotativo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Periodo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("VigenteDesde")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime(6)");

                    b.HasKey("HorarioId");

                    b.HasIndex("BomberoId");

                    b.ToTable("HorariosBomberos", (string)null);
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Imagen", b =>
                {
                    b.Property<int>("ImagenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImagenId"));

                    b.Property<string>("Base64Imagen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreImagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoImagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoImagenDiscriminador")
                        .HasColumnType("int");

                    b.HasKey("ImagenId");

                    b.ToTable("Imagenes", (string)null);

                    b.HasDiscriminator<int>("TipoImagenDiscriminador");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.MovilSalida", b =>
                {
                    b.Property<int>("MovilSalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MovilSalidaId"));

                    b.Property<string>("CantidadLitros")
                        .HasColumnType("longtext");

                    b.Property<bool>("CargoCombustible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DotacionSalida")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaFactura")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KmLlegada")
                        .HasColumnType("int");

                    b.Property<int>("MovilId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("QuienLleno")
                        .HasColumnType("longtext");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoQuienLleno")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoConbustible")
                        .HasColumnType("longtext");

                    b.HasKey("MovilSalidaId");

                    b.HasIndex("MovilId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("SalidaId");

                    b.ToTable("MovilesSalida");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.NovedadBase", b =>
                {
                    b.Property<int>("NovedadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NovedadId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<int?>("PersonalId")
                        .HasColumnType("int");

                    b.HasKey("NovedadId");

                    b.HasIndex("PersonalId");

                    b.ToTable("NovedadBase");

                    b.HasDiscriminator().HasValue("NovedadBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonaId"));

                    b.Property<int?>("Altura")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Documento")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LugarNacimiento")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NivelEstudios")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroIoma")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("Profesion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("int");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas", (string)null);

                    b.HasDiscriminator<int>("TipoPersona").HasValue(2);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<int?>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Patente")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SeguroId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("int");

                    b.HasKey("VehiculoId");

                    b.HasIndex("SeguroId")
                        .IsUnique();

                    b.ToTable("Vehiculo");

                    b.HasDiscriminator<int>("TipoVehiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.AscensoBombero", b =>
                {
                    b.Property<int>("AscensoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AscensoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GradoAntiguo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GradoAscenso")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("AscensoId");

                    b.HasIndex("PersonaId");

                    b.ToTable("AscensoBombero", (string)null);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Damnificado", b =>
                {
                    b.Property<int>("DamnificadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DamnificadoId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LugarDeNacimiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("DamnificadoId");

                    b.HasIndex("SalidaId");

                    b.ToTable("Damnificados");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.EmbarcacionAfectada", b =>
                {
                    b.Property<int>("EmbarcacionAfectadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmbarcacionAfectadaId"));

                    b.Property<int>("CantidadBarcos")
                        .HasColumnType("int");

                    b.Property<int>("CantidadBotes")
                        .HasColumnType("int");

                    b.Property<int>("CantidadFragatas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadLanchas")
                        .HasColumnType("int");

                    b.Property<bool>("Intervinientes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Otro")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasKey("EmbarcacionAfectadaId");

                    b.HasIndex("SalidaId");

                    b.ToTable("EmbarcacionesAfectadas");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FirmaId"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EmbarcacionVehiculoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("FirmaId");

                    b.HasIndex("EmbarcacionVehiculoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Firmas");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Incidente", b =>
                {
                    b.Property<int>("IncidenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IncidenteId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("IncidenteId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Incidente", (string)null);

                    b.HasDiscriminator().HasValue("Incidente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Licencia", b =>
                {
                    b.Property<int>("LicenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LicenciaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Desde")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EstadoLicencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Hasta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoLicencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("LicenciaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Licencias", (string)null);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Limpieza", b =>
                {
                    b.Property<int>("LimpiezaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LimpiezaId"));

                    b.Property<int?>("BomberosPersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Incidente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MovilId")
                        .HasColumnType("int");

                    b.HasKey("LimpiezaId");

                    b.HasIndex("BomberosPersonaId");

                    b.HasIndex("MovilId");

                    b.ToTable("Limpiezas");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rubro")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.MovimientoMaterial", b =>
                {
                    b.Property<int>("MovimientoMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MovimientoMaterialId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("DestinoBomberoPersonaId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinoMovilVehiculoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MaterialesMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MovimientoMaterialId");

                    b.HasIndex("DestinoBomberoPersonaId");

                    b.HasIndex("DestinoMovilVehiculoId");

                    b.HasIndex("MaterialesMaterialId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Sancion", b =>
                {
                    b.Property<int>("SancionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SancionId"));

                    b.Property<int>("EncargadoAreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("SacionArea")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoSancion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SancionId");

                    b.HasIndex("EncargadoAreaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Sanciones", (string)null);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Seguro", b =>
                {
                    b.Property<int>("SeguroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SeguroId"));

                    b.Property<string>("CompañiaAseguradora")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaDeVencimineto")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroDePoliza")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoSeguro")
                        .HasColumnType("int");

                    b.HasKey("SeguroId");

                    b.ToTable("Seguros", (string)null);

                    b.HasDiscriminator<int>("TipoSeguro");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.Property<int>("SalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SalidaId"));

                    b.Property<int>("AnioNumeroParte")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CalleORuta")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Depto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DniSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EncargadoId")
                        .HasColumnType("int");

                    b.Property<string>("EntreCalles")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("HoraLlegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double");

                    b.Property<string>("NombreSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreYApellidoReceptor")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroOKilometro")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumeroParte")
                        .HasColumnType("int");

                    b.Property<string>("PisoNumero")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QuienLlenoId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceptorId")
                        .HasColumnType("int");

                    b.Property<int?>("SeguroId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoSalida")
                        .HasColumnType("int");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.Property<string>("TipoZona")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SalidaId");

                    b.HasIndex("EncargadoId");

                    b.HasIndex("QuienLlenoId");

                    b.HasIndex("ReceptorId");

                    b.HasIndex("SeguroId")
                        .IsUnique();

                    b.ToTable("Salidas", (string)null);

                    b.HasDiscriminator<int>("TipoSalida");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.ImagenBombero", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.Imagen");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.ImagenVehiculo", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.Imagen");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Novedad", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.NovedadBase");

                    b.HasDiscriminator().HasValue("Novedad");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.NovedadVehiculo", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.NovedadBase");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasIndex("VehiculoId");

                    b.HasDiscriminator().HasValue("NovedadVehiculo");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Bombero", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.Persona");

                    b.Property<int?>("BrigadaId")
                        .HasColumnType("int");

                    b.Property<bool>("Chofer")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Dotacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ImagenId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroLegajo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VencimientoRegistro")
                        .HasColumnType("datetime(6)");

                    b.HasIndex("BrigadaId");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.HasIndex("ImagenId")
                        .IsUnique();

                    b.HasIndex("NumeroLegajo")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.VehiculoPersonal", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.Vehiculo");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasIndex("PersonaId");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.VehiculoSalida", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.Vehiculo");

                    b.Property<int?>("EncargadoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ImagenId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroMovil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasIndex("EncargadoId");

                    b.HasIndex("ImagenId")
                        .IsUnique();
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.VehiculoAfectado", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.Vehiculo");

                    b.Property<bool>("Airbag")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SalidaId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.VehiculoDamnificado", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.Vehiculo");

                    b.Property<bool>("Airbag")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DamnificadoId")
                        .HasColumnType("int");

                    b.HasIndex("DamnificadoId")
                        .IsUnique();

                    b.ToTable("Vehiculo", t =>
                        {
                            t.Property("Airbag")
                                .HasColumnName("VehiculoDamnificado_Airbag");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.IncidenteDependencia", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Componentes.Incidente");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("int");

                    b.HasIndex("DependenciaId");

                    b.HasDiscriminator().HasValue("IncidenteDependencia");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.SeguroSalida", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Componentes.Seguro");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.SeguroVehiculo", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Componentes.Seguro");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.Accidente", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("CondicionesClimaticas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroCondicion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Accidente_Tipo");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.FactorClimatico", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Salida");

                    b.Property<int>("CantidadAfectadaFactorClimatico")
                        .HasColumnType("int");

                    b.Property<string>("Evacuacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Superficie")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Evacuacion")
                                .HasColumnName("FactorClimatico_Evacuacion");

                            t.Property("Tipo")
                                .HasColumnName("FactorClimatico_Tipo");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.Incendio", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Salida");

                    b.Property<int?>("CantidadAmbientes")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadPisos")
                        .HasColumnType("int");

                    b.Property<string>("DetalleSuperficieAfectadaIncendio")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("DeteccionAutomaticaId")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Extintor")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Hidrante")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreEstablecimiento")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtraAbertura")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroLugarIncendio")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroTecho")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PisoAfectado")
                        .HasColumnType("int");

                    b.Property<string>("SuperficieAfectadaCausa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoAbertura")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoEvacuacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoSuperficieAfectada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoTecho")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Incendio_Tipo");
                        });

                    b.HasDiscriminator().HasValue(15);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.MaterialPeligroso", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Salida");

                    b.Property<int>("CantidadAfectadaMaterialPeligroso")
                        .HasColumnType("int");

                    b.Property<bool>("Confinamiento")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Controlada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Descontaminacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DetallesAccionesMateriales")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DetallesAccionesPersonas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("DilucionDeVapores")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Evacuacion")
                        .HasColumnType("int");

                    b.Property<bool>("Neutralizacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OtraAccionesMateriales")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OtraAccionesPersonas")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SinAccion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sustancias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoSituacion")
                        .HasColumnType("int");

                    b.Property<int>("TipoSuperficie")
                        .HasColumnType("int");

                    b.Property<bool>("Trasvase")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Venteo")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.RescateAnimal", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("LugarRescateAnimal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroLugarRescate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.RescatePersona", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("LugarRescatePersona")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OtroLugarRescate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.ServicioEspecial", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Salida");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoOrganizacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("ServicioEspecial_Tipo");
                        });

                    b.HasDiscriminator().HasValue(16);
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Movil", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.VehiculoSalida");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<string>("ModeloBomba")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroChasis")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroMotor")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.HasIndex("NumeroMovil")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Embarcacion", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Personales.VehiculoSalida");

                    b.HasIndex("NumeroMovil")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.VehiculoAfectadoAccidente", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Componentes.VehiculoAfectado");

                    b.HasIndex("SalidaId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.VehiculoAfectadoIncendio", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Componentes.VehiculoAfectado");

                    b.HasIndex("SalidaId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.IncendioAeronaves", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Incendio");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Incendio_Tipo");
                        });

                    b.HasDiscriminator().HasValue(17);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.IncendioComercio", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Incendio_Tipo");
                        });

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.IncendioEstablecimientoEducativo", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Incendio_Tipo");

                            t.Property("TipoLugar")
                                .HasColumnName("IncendioEstablecimientoEducativo_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.IncendioEstablecimientoPublico", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Incendio_Tipo");

                            t.Property("TipoLugar")
                                .HasColumnName("IncendioEstablecimientoPublico_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(9);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.IncendioForestal", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Incendio_Tipo");

                            t.Property("TipoLugar")
                                .HasColumnName("IncendioForestal_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(10);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.IncendioHospitalesYClinicas", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Incendio_Tipo");

                            t.Property("TipoLugar")
                                .HasColumnName("IncendioHospitalesYClinicas_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(11);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.IncendioIndustria", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Incendio_Tipo");

                            t.Property("TipoLugar")
                                .HasColumnName("IncendioIndustria_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(12);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.IncendioVivienda", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.Incendio");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("Incendio_Tipo");

                            t.Property("TipoLugar")
                                .HasColumnName("IncendioVivienda_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(13);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.ServicioEspecialCapacitacion", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.ServicioEspecial");

                    b.Property<DateTime>("DiaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NivelDeCapacitacion")
                        .HasColumnType("int");

                    b.Property<string>("NivelDeCapacitacionOtro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoCapacitacion")
                        .HasColumnType("int");

                    b.Property<string>("TipoCapacitacionOtra")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("ServicioEspecial_Tipo");
                        });

                    b.HasDiscriminator().HasValue(18);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.ServicioEspecialColocaciónDriza", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.ServicioEspecial");

                    b.Property<string>("Detalles")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreEstablecimiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("ServicioEspecial_Tipo");

                            t.Property("NombreEstablecimiento")
                                .HasColumnName("ServicioEspecialColocaciónDriza_NombreEstablecimiento");

                            t.Property("TipoLugar")
                                .HasColumnName("ServicioEspecialColocaciónDriza_TipoLugar");
                        });

                    b.HasDiscriminator().HasValue(19);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.ServicioEspecialPrevencion", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.ServicioEspecial");

                    b.Property<string>("TipoPrevencion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("ServicioEspecial_Tipo");
                        });

                    b.HasDiscriminator().HasValue(14);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.ServicioEspecialRepresentacion", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.ServicioEspecial");

                    b.Property<string>("TipoRepresentacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("ServicioEspecial_Tipo");
                        });

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.ServicioEspecialSuministroAgua", b =>
                {
                    b.HasBaseType("Vista.Data.Models.Salidas.Planillas.ServicioEspecial");

                    b.Property<string>("DetallesSuministroAgua")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreEstablecimientoSuministroAgua")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("Salidas", t =>
                        {
                            t.Property("Tipo")
                                .HasColumnName("ServicioEspecial_Tipo");
                        });

                    b.HasDiscriminator().HasValue(20);
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.BomberoDependencia", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Dependencia", "Dependencia")
                        .WithMany("Bomberos")
                        .HasForeignKey("DependenciaId");

                    b.HasOne("Vista.Data.Models.Personales.Bombero", "Bombero")
                        .WithOne("Dependencia")
                        .HasForeignKey("Vista.Data.Models.Personales.BomberoDependencia", "PersonaId");

                    b.Navigation("Bombero");

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.BomberoSalida", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Movil", "MovilAsignado")
                        .WithMany()
                        .HasForeignKey("MovilId");

                    b.HasOne("Vista.Data.Models.Personales.Bombero", "Bombero")
                        .WithMany("Salidas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("CuerpoParticipante")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("MovilAsignado");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Contacto", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Persona", "Persona")
                        .WithOne("Contacto")
                        .HasForeignKey("Vista.Data.Models.Personales.Contacto", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.FuerzaInterviniente", b =>
                {
                    b.HasOne("Vista.Data.Models.Salidas.Componentes.Damnificado", "Damnificado")
                        .WithMany()
                        .HasForeignKey("DamnificadoId");

                    b.HasOne("Vista.Data.Models.Personales.Fuerza", "Fuerza")
                        .WithMany()
                        .HasForeignKey("FuerzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany()
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Data.Models.Personales.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Damnificado");

                    b.Navigation("Fuerza");

                    b.Navigation("Salida");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.HorarioBombero", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", null)
                        .WithMany("Horarios")
                        .HasForeignKey("BomberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.MovilSalida", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Movil", "Movil")
                        .WithMany("Salidas")
                        .HasForeignKey("MovilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Data.Models.Personales.Bombero", "Chofer")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("Moviles")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chofer");

                    b.Navigation("Movil");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.NovedadBase", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", "Personal")
                        .WithMany("Novedades")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Vehiculo", b =>
                {
                    b.HasOne("Vista.Data.Models.Salidas.Componentes.SeguroVehiculo", "Seguro")
                        .WithOne("Vehiculo")
                        .HasForeignKey("Vista.Data.Models.Personales.Vehiculo", "SeguroId");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.AscensoBombero", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", "PersonalAfectado")
                        .WithMany("Ascensos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalAfectado");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Damnificado", b =>
                {
                    b.HasOne("Vista.Data.Models.Salidas.Planillas.Salida", "Salida")
                        .WithMany("Damnificados")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.EmbarcacionAfectada", b =>
                {
                    b.HasOne("Vista.Data.Models.Salidas.Planillas.Incendio", "Incendio")
                        .WithMany()
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incendio");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Firma", b =>
                {
                    b.HasOne("Vista.Data.Models.Salidas.Componentes.Embarcacion", null)
                        .WithMany("Firmas")
                        .HasForeignKey("EmbarcacionVehiculoId");

                    b.HasOne("Vista.Data.Models.Personales.Bombero", "Bombero")
                        .WithMany("Firmas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Data.Models.Personales.Movil", "Movil")
                        .WithMany("Firmas")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Incidente", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", "Encargado")
                        .WithMany("Incidentes")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vista.Data.Models.Personales.VehiculoSalida", "Vehiculo")
                        .WithMany("Incidentes")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Encargado");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Licencia", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", "PersonalAfectado")
                        .WithMany("Licencias")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalAfectado");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Limpieza", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", "Bomberos")
                        .WithMany("Limpieza")
                        .HasForeignKey("BomberosPersonaId");

                    b.HasOne("Vista.Data.Models.Personales.Movil", "Movil")
                        .WithMany()
                        .HasForeignKey("MovilId");

                    b.Navigation("Bomberos");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.MovimientoMaterial", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", "DestinoBombero")
                        .WithMany("DestinoMaterial")
                        .HasForeignKey("DestinoBomberoPersonaId");

                    b.HasOne("Vista.Data.Models.Personales.Movil", "DestinoMovil")
                        .WithMany()
                        .HasForeignKey("DestinoMovilVehiculoId");

                    b.HasOne("Vista.Data.Models.Salidas.Componentes.Material", "Materiales")
                        .WithMany()
                        .HasForeignKey("MaterialesMaterialId");

                    b.Navigation("DestinoBombero");

                    b.Navigation("DestinoMovil");

                    b.Navigation("Materiales");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Sancion", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", "EncargadoArea")
                        .WithMany("SancionesAplicadas")
                        .HasForeignKey("EncargadoAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Data.Models.Personales.Bombero", "PersonalSancionado")
                        .WithMany("SancionesRecibidas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncargadoArea");

                    b.Navigation("PersonalSancionado");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", "Encargado")
                        .WithMany()
                        .HasForeignKey("EncargadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Data.Models.Personales.Bombero", "QuienLleno")
                        .WithMany()
                        .HasForeignKey("QuienLlenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vista.Data.Models.Personales.Bombero", "ReceptorBombero")
                        .WithMany()
                        .HasForeignKey("ReceptorId");

                    b.HasOne("Vista.Data.Models.Salidas.Componentes.SeguroSalida", "Seguro")
                        .WithOne("Salida")
                        .HasForeignKey("Vista.Data.Models.Salidas.Planillas.Salida", "SeguroId");

                    b.Navigation("Encargado");

                    b.Navigation("QuienLleno");

                    b.Navigation("ReceptorBombero");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.NovedadVehiculo", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.VehiculoSalida", "Vehiculo")
                        .WithMany("Novedades")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Bombero", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Brigada", "Brigada")
                        .WithMany("Bomberos")
                        .HasForeignKey("BrigadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vista.Data.Models.Personales.Comunicacion", "Handie")
                        .WithOne("Bombero")
                        .HasForeignKey("Vista.Data.Models.Personales.Bombero", "EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vista.Data.Models.Personales.ImagenBombero", "Imagen")
                        .WithOne("Bombero")
                        .HasForeignKey("Vista.Data.Models.Personales.Bombero", "ImagenId");

                    b.Navigation("Brigada");

                    b.Navigation("Handie");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.VehiculoPersonal", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", "Bombero")
                        .WithMany("Vehiculos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.VehiculoSalida", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Bombero", "Encargado")
                        .WithMany("VehiculosEncargado")
                        .HasForeignKey("EncargadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vista.Data.Models.Personales.ImagenVehiculo", "Imagen")
                        .WithOne("Vehiculo")
                        .HasForeignKey("Vista.Data.Models.Personales.VehiculoSalida", "ImagenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Encargado");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.VehiculoDamnificado", b =>
                {
                    b.HasOne("Vista.Data.Models.Salidas.Componentes.Damnificado", "Damnificado")
                        .WithOne("VehiculoDamnificado")
                        .HasForeignKey("Vista.Data.Models.Salidas.Componentes.VehiculoDamnificado", "DamnificadoId");

                    b.Navigation("Damnificado");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.IncidenteDependencia", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Dependencia", "Dependencia")
                        .WithMany("Incidentes")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Movil", b =>
                {
                    b.HasOne("Vista.Data.Models.Personales.Comunicacion", "HandieMovil")
                        .WithOne("Movil")
                        .HasForeignKey("Vista.Data.Models.Personales.Movil", "EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HandieMovil");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.VehiculoAfectadoAccidente", b =>
                {
                    b.HasOne("Vista.Data.Models.Salidas.Planillas.Accidente", "Accidente")
                        .WithMany("VehiculosAfectado")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accidente");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.VehiculoAfectadoIncendio", b =>
                {
                    b.HasOne("Vista.Data.Models.Salidas.Planillas.Incendio", "Incendio")
                        .WithMany("VehiculoAfectados")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incendio");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Brigada", b =>
                {
                    b.Navigation("Bomberos");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Comunicacion", b =>
                {
                    b.Navigation("Bombero");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Dependencia", b =>
                {
                    b.Navigation("Bomberos");

                    b.Navigation("Incidentes");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Persona", b =>
                {
                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Damnificado", b =>
                {
                    b.Navigation("VehiculoDamnificado");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.Salida", b =>
                {
                    b.Navigation("CuerpoParticipante");

                    b.Navigation("Damnificados");

                    b.Navigation("Moviles");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.ImagenBombero", b =>
                {
                    b.Navigation("Bombero")
                        .IsRequired();
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.ImagenVehiculo", b =>
                {
                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Bombero", b =>
                {
                    b.Navigation("Ascensos");

                    b.Navigation("Dependencia");

                    b.Navigation("DestinoMaterial");

                    b.Navigation("Firmas");

                    b.Navigation("Horarios");

                    b.Navigation("Incidentes");

                    b.Navigation("Licencias");

                    b.Navigation("Limpieza");

                    b.Navigation("Novedades");

                    b.Navigation("Salidas");

                    b.Navigation("SancionesAplicadas");

                    b.Navigation("SancionesRecibidas");

                    b.Navigation("Vehiculos");

                    b.Navigation("VehiculosEncargado");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.VehiculoSalida", b =>
                {
                    b.Navigation("Incidentes");

                    b.Navigation("Novedades");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.SeguroSalida", b =>
                {
                    b.Navigation("Salida")
                        .IsRequired();
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.SeguroVehiculo", b =>
                {
                    b.Navigation("Vehiculo")
                        .IsRequired();
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.Accidente", b =>
                {
                    b.Navigation("VehiculosAfectado");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Planillas.Incendio", b =>
                {
                    b.Navigation("VehiculoAfectados");
                });

            modelBuilder.Entity("Vista.Data.Models.Personales.Movil", b =>
                {
                    b.Navigation("Firmas");

                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("Vista.Data.Models.Salidas.Componentes.Embarcacion", b =>
                {
                    b.Navigation("Firmas");
                });
#pragma warning restore 612, 618
        }
    }
}
